Description of ample
Home > AMPLE_1.1 > ample.m
ample
PURPOSE
AMPLE 1.1: A Material Point Learning Environment
SYNOPSIS
This is a script file.
DESCRIPTION
AMPLE 1.1: A Material Point Learning Environment
--------------------------------------------------------------------------
 Author: William Coombs
 Date:   27/08/2020
 Description:
 Large deformation elasto-plastic (EP) material point method (MPM) code
 based on an updated Lagrangian (UL) descripition of motion with a
 quadrilateral background mesh.
--------------------------------------------------------------------------
 See also:
 SETUPGRID             - analysis specific information
 ELEMMPINFO            - material point-element information
 DETEXTFORCE           - external forces
 DETFDOFS              - mesh unknown degrees of freedom
 LINSOLVE              - linear solver
 DETMPS                - material point stiffness and internal force
 UPDATEMPS             - update material points
 POSTPRO               - post processing function including vtk output
--------------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
detExtForce Global external force determination
detFDoFs Determine the free degrees of freedom on the background mesh
detMPs Stiffness and internal force calculation for all material points
elemMPinfo Determine the basis functions for material points
linSolve Linear solver
updateMPs Material point update: stress, position and volume
postPro Post processing script for the AMPLE code
setupGrid Problem setup information
This function is called by:
SOURCE CODE
%AMPLE 1.1: A Material Point Learning Environment
%--------------------------------------------------------------------------
% Author: William Coombs
% Date:   27/08/2020
% Description:
% Large deformation elasto-plastic (EP) material point method (MPM) code
% based on an updated Lagrangian (UL) descripition of motion with a
% quadrilateral background mesh.
%
%--------------------------------------------------------------------------
% See also:
% SETUPGRID             - analysis specific information
% ELEMMPINFO            - material point-element information
% DETEXTFORCE           - external forces
% DETFDOFS              - mesh unknown degrees of freedom
% LINSOLVE              - linear solver
% DETMPS                - material point stiffness and internal force
% UPDATEMPS             - update material points
% POSTPRO               - post processing function including vtk output
%--------------------------------------------------------------------------
clear;
addpath('constitutive','functions','plotting','setup');
[lstps,g,mpData,mesh] = setupGrid;                                          % setup information
NRitMax = 10; tol = 1e-9;                                                   % Newton Raphson parameters
[nodes,nD] = size(mesh.coord);                                              % number of nodes and dimensions
[nels,nen] = size(mesh.etpl);                                               % number of elements and nodes/element
nDoF = nodes*nD;                                                            % total number of degrees of freedom
nmp  = length(mpData);                                                      % number of material points
lstp = 0;                                                                   % zero loadstep counter (for plotting function)
run postPro;                                                                % plotting initial state & mesh
for lstp=1:lstps                                                            % loadstep loop
  fprintf(1,'\n%s %4i %s %4i\n','loadstep ',lstp,' of ',lstps);             % text output to screen (loadstep)
  [mesh,mpData] = elemMPinfo(mesh,mpData);                                  % material point - element information
  fext = detExtForce(nodes,nD,g,mpData);                                    % external force calculation (total)
  fext = fext*lstp/lstps;                                                   % current external force value
  oobf = fext;                                                              % initial out-of-balance force
  fErr = 1;                                                                 % initial error
  frct = zeros(nDoF,1);                                                     % zero the reaction forces
  uvw  = zeros(nDoF,1);                                                     % zero the displacements
  fd   = detFDoFs(mesh);                                                    % free degrees of freedom
  NRit = 0;                                                                 % zero the iteration counter
  Kt   = 0;                                                                 % zero global stiffness matrix
  while (fErr > tol) && (NRit < NRitMax) || (NRit < 2)                      % global equilibrium loop
    [duvw,drct] = linSolve(mesh.bc,Kt,oobf,NRit,fd);                        % linear solver
    uvw  = uvw+duvw;                                                        % update displacements
    frct = frct+drct;                                                       % update reaction forces
    [fint,Kt,mpData] = detMPs(uvw,mpData,nD);                               % global stiffness & internal force
    oobf = (fext-fint+frct);                                                % out-of-balance force
    fErr = norm(oobf)/norm(fext+frct+eps);                                  % normalised oobf error
    NRit = NRit+1;                                                          % increment the NR counter
    fprintf(1,'%s %2i %s %8.3e\n','  iteration ',NRit,' NR error ',fErr);   % text output to screen (NR error)
  end
  mpData = updateMPs(uvw,mpData);                                           % update material points
  run postPro;                                                              % Plotting and post processing
end