Description of setupGrid
Home > AMPLE > setup > setupGrid.m
setupGrid
PURPOSE
Problem setup information
SYNOPSIS
function [lstps,g,mpData,mesh] = setupGrid
DESCRIPTION
Problem setup information
--------------------------------------------------------------------------
 Author: William Coombs
 Date:   29/01/2019
 Description:
 Problem setup for the compaction of a 2D column under self weight with
 roller boundary conditions applied to the sides and the base of the
 domain.
--------------------------------------------------------------------------
 [lstps,g,mpData,mesh] = SETUPGRID
--------------------------------------------------------------------------
 Input(s):
--------------------------------------------------------------------------
 Ouput(s);
 lstps  - number of loadsteps (1)
 g      - gravity (1)
 mpData - structured array with the following fields:
           - mpType : material point type (1 = MPM, 2 = GIMPM)
           - cmType : constitutive model type (1 = elastic, 2 = vM plas.)
           - mpC    : material point coordinates
           - vp     : material point volume
           - vp0    : initial material point volume
           - mpM    : material point mass
           - nIN    : nodes linked to the material point
           - eIN    : element associated with the material point
           - nSMe   : number of stiffness matrix entries for the MP
           - Svp    : basis functions for the material point
           - dSvp   : basis function derivatives (at start of lstp)
           - Fn     : previous deformation gradient
           - F      : deformation gradient
           - sig    : Cauchy stress
           - epsEn  : previous logarithmic elastic strain
           - epsE   : logarithmic elastic strain
           - mCst   : material constants (or internal state parameters)
           - fp     : force at the material point
           - u      : material point displacement
           - lp     : material point domain lengths
           - lp0    : initial material point domain lengths
 mesh   - structured array with the following fields
           - coord : mesh nodal coordinates (nodes,nD)
           - etpl  : element topology (nels,nen)
           - bc    : boundary conditions (*,2)
           - h     : background mesh size (nD,1)
--------------------------------------------------------------------------
 See also:
 FORMCOORD2D - background mesh generation
 DETMPPOS    - local material point positions
 SHAPEFUNC   - background grid basis functions
--------------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
detMpPos Material point local positions for point generation
formCoord2D Two dimensional finite element grid generation
shapefunc Finite element basis functions
This function is called by:
ample AMPLE: A Material Point Learning Environment
SOURCE CODE
function [lstps,g,mpData,mesh] = setupGrid
%Problem setup information
%--------------------------------------------------------------------------
% Author: William Coombs
% Date:   29/01/2019
% Description:
% Problem setup for the compaction of a 2D column under self weight with
% roller boundary conditions applied to the sides and the base of the
% domain.
%
%--------------------------------------------------------------------------
% [lstps,g,mpData,mesh] = SETUPGRID
%--------------------------------------------------------------------------
% Input(s):
%
%--------------------------------------------------------------------------
% Ouput(s);
% lstps  - number of loadsteps (1)
% g      - gravity (1)
% mpData - structured array with the following fields:
%           - mpType : material point type (1 = MPM, 2 = GIMPM)
%           - cmType : constitutive model type (1 = elastic, 2 = vM plas.)
%           - mpC    : material point coordinates
%           - vp     : material point volume
%           - vp0    : initial material point volume
%           - mpM    : material point mass
%           - nIN    : nodes linked to the material point
%           - eIN    : element associated with the material point
%           - nSMe   : number of stiffness matrix entries for the MP
%           - Svp    : basis functions for the material point
%           - dSvp   : basis function derivatives (at start of lstp)
%           - Fn     : previous deformation gradient
%           - F      : deformation gradient
%           - sig    : Cauchy stress
%           - epsEn  : previous logarithmic elastic strain
%           - epsE   : logarithmic elastic strain
%           - mCst   : material constants (or internal state parameters)
%           - fp     : force at the material point
%           - u      : material point displacement
%           - lp     : material point domain lengths
%           - lp0    : initial material point domain lengths
%
% mesh   - structured array with the following fields
%           - coord : mesh nodal coordinates (nodes,nD)
%           - etpl  : element topology (nels,nen)
%           - bc    : boundary conditions (*,2)
%           - h     : background mesh size (nD,1)
%--------------------------------------------------------------------------
% See also:
% FORMCOORD2D - background mesh generation
% DETMPPOS    - local material point positions
% SHAPEFUNC   - background grid basis functions
%--------------------------------------------------------------------------
%% Analysis parameters
E      = 1e4;   v = 0;                                                      % Young's modulus, Poisson's ratio
mCst   = [E v];                                                             % material constants
g      = 10;                                                                % gravity
rho    = 80;                                                                % material density
lstps  = 40;                                                                % number of loadsteps
nelsx  = 1;                                                                 % number of elements in the x direction
nelsy  = 2^6;                                                               % number of elements in the y direction
ly     = 50;  lx = ly/nelsy;                                                % domain dimensions
mp     = 2;                                                                 % number of material points in each direction per element
mpType = 2;                                                                 % material point type: 1 = MPM, 2 = GIMP
cmType = 1;                                                                 % constitutive model: 1 = elastic, 2 = vM plasticity
%% Mesh generation
[etpl,coord] = formCoord2D(nelsx,nelsy,lx,ly);                              % background mesh generation
[~,nen]      = size(etpl);                                                  % number of element nodes
[nodes,nD]   = size(coord);                                                 % number of nodes and dimensions
h            = [lx ly]./[nelsx nelsy];                                      % element lengths in each direction
%% Boundary conditions on background mesh
bc = zeros(nodes*nD,2);                                                     % generate empty bc matrix
for node=1:nodes                                                            % loop over nodes
  if coord(node,1)==0 || coord(node,1)==lx                                  % roller sides
    bc(node*2-1,:)=[node*2-1 0];
  end
  if coord(node,2)==0                                                       % roller base
    bc(node*2  ,:)=[node*2   0];
  end
end
bc = bc(bc(:,1)>0,:);                                                       % remove empty part of bc
%% Mesh data structure generation
mesh.etpl  = etpl;                                                          % element topology
mesh.coord = coord;                                                         % nodal coordinates
mesh.bc    = bc;                                                            % boundary conditions
mesh.h     = h;                                                             % mesh size
%% Material point generation
ngp    = mp^nD;                                                             % number of material points per element
GpLoc  = detMpPos(mp,nD);                                                   % local MP locations (for each element)
N      = shapefunc(nen,GpLoc,nD);                                           % basis functions for the material points
[etplmp,coordmp] = formCoord2D(nelsx,nelsy,lx,ly);                          % mesh for MP generation
nelsmp = size(etplmp,1);                                                    % no. elements populated with material points
nmp    = ngp*nelsmp;                                                        % total number of mterial points
mpC=zeros(nmp,nD);                                                          % zero MP coordinates
for nel=1:nelsmp
  indx=(nel-1)*ngp+1:nel*ngp;                                               % MP locations within mpC
  eC=coordmp(etplmp(nel,:),:);                                              % element coordinates
  mpPos=N*eC;                                                               % global MP coordinates
  mpC(indx,:)=mpPos;                                                        % store MP positions
end
lp = zeros(nmp,2);                                                          % zero domain lengths
lp(:,1) = h(1)/(2*mp);                                                      % domain half length x-direction
lp(:,2) = h(2)/(2*mp);                                                      % domain half length y-direction
vp      = 2^nD*lp(:,1).*lp(:,2);                                            % volume associated with each material point
%% Material point structure generation
for mp = nmp:-1:1                                                           % loop backwards over MPs so array doesn't change size
  mpData(mp).mpType = mpType;                                               % material point type: 1 = MPM, 2 = GIMP
  mpData(mp).cmType = cmType;                                               % constitutive model: 1 = elastic, 2 = vM plasticity
  mpData(mp).mpC    = mpC(mp,:);                                            % material point coordinates
  mpData(mp).vp     = vp(mp);                                               % material point volume
  mpData(mp).vp0    = vp(mp);                                               % material point initial volume
  mpData(mp).mpM    = vp(mp)*rho;                                           % material point mass
  mpData(mp).nIN    = zeros(nen,1);                                         % nodes associated with the material point
  mpData(mp).eIN    = 0;                                                    % element associated with the material point
  mpData(mp).nSMe   = 0;                                                    % number of stiffness entries associated with the material point
  mpData(mp).Svp    = zeros(1,nen);                                         % material point basis functions
  mpData(mp).dSvp   = zeros(nD,nen);                                        % derivative of the basis functions
  mpData(mp).Fn     = eye(3);                                               % previous deformation gradient
  mpData(mp).F      = eye(3);                                               % deformation gradient
  mpData(mp).sig    = zeros(6,1);                                           % Cauchy stress
  mpData(mp).epsEn  = zeros(6,1);                                           % previous elastic strain (logarithmic)
  mpData(mp).epsE   = zeros(6,1);                                           % elastic strain (logarithmic)
  mpData(mp).mCst   = mCst;                                                 % material constants (or internal variables) for constitutive model
  mpData(mp).fp     = zeros(nD,1);                                          % point forces at material points
  mpData(mp).u      = zeros(nD,1);                                          % material point displacements
  if mpData(mp).mpType == 2
    mpData(mp).lp     = lp(mp,:);                                           % material point domain lengths (GIMP)
    mpData(mp).lp0    = lp(mp,:);                                           % initial material point domain lengths (GIMP)
  else
    mpData(mp).lp     = zeros(1,nD);                                        % material point domain lengths (MPM)
    mpData(mp).lp0    = zeros(1,nD);                                        % initial material point domain lengths (MPM)
  end
end